## ALIAS SETTINGS ##
alias soprof='source ~/.bash_profile'
alias viprof='vim ~/.bash_profile'

alias vibash='vim ~/.bashrc'
alias vivim='vim ~/.vimrc'
alias vial='vim ~/.bash_aliases'
alias vialloc='vim ~/.bash_aliases.local'

alias vidot='vim ~/repo/dotfiles/dotfiles'

if [[ "$(uname -s)" == "Darwin" ]]; then
    alias l='ls -GFh'
    #--color=auto'
elif [[ "$(uname -s)" == "Linux" ]]; then
    alias l='ls --color=auto'
fi

alias hidden='ls -ld .*'

alias tmuxx='tmux -2'        # allows 256 colors for vim to work in tmux

alias freemacs='pkill -SIGUSR2 Emacs' # unfreeze emacs from hanging

# notes
alias n='vim ~/Dropbox/.note'
alias notes='cd ~/Dropbox/notes/'

# GIT
alias g='git'
alias add='git add'
alias commit='git commit'
alias st='git status'
alias branch='git branch'
alias checkout='git checkout'

# General
alias v='vim'

# Trash
alias mktrash='mkdir -p ~/.Trash'
alias trash='mktrash; mv -t ~/.Trash'
alias t='trash'
alias trash-empty='mktrash; rm -r ~/.Trash'
alias trash-list='mktrash; ls -A ~/.Trash'
# gitit
alias gi='cd ~/wiki && gitit'

# VERCON 
alias vc='bash ~/repo/vercon/vercon.sh'
