## ALIAS SETTINGS ##
alias soprof='source ~/.bash_profile'
alias viprof='vim ~/.bash_profile'

alias vibash='vim ~/.bashrc'
alias vivim='vim ~/.vimrc'
alias vial='vim ~/.bash_aliases'
alias vialloc='vim ~/.bash_aliases.local'

alias vidot='vim ~/repo/dotfiles/dotfiles'
alias cddot='cd ~/repo/dotfiles/dotfiles'

if [[ "$(uname -s)" == "Darwin" ]]; then
    alias l='ls -GFh'
    #--color=auto'
elif [[ "$(uname -s)" == "Linux" ]]; then
    alias l='ls --color=auto'
fi

alias hidden='ls -ld .*'

alias tmuxx='tmux -2'        # allows 256 colors for vim to work in tmux

alias freemacs='pkill -SIGUSR2 Emacs' # unfreeze emacs from hanging

# notes
alias nn='vim ~/Dropbox/.note'
alias cn='cat ~/Dropbox/.note'
alias notes='cd ~/Dropbox/notes/'

# GIT
alias g='git'
alias ga='git add'
alias gc='git commit'
alias st='git status'
alias gb='git branch'
alias gco='git checkout'
alias gm='git merge'
alias gp="git pull"

alias gclean=git-clean

# General
alias v='vim'

# Trash
alias mktrash='mkdir -p ~/.Trash'
alias trash='mktrash; mv -t ~/.Trash'
alias t='trash'
alias trash-empty='mktrash; rm -r ~/.Trash'
alias trash-list='mktrash; ls -A ~/.Trash'

# JAVA
alias find-class=find-class

## Bash Functions
function git-clean {
    git branch --merged master | grep -v 'master$' | xargs git branch -d
}
function find-class {
    find . -name '*.jar' -exec grep -Hls $1 {} \;
}
